on: push
name: Tests
jobs:
  gitHubActionForUnittest:
    name: GitHub Action for Python unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip3 install setuptools && pip3 install -r requirements.txt
    - name: Run unit tests
      run: python3 -m unittest discover -v
