on: push
name: build
jobs:
  build:
#     name: GitHub Action for Python unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip3 install setuptools && pip3 install -r requirements.txt
      - name: Run unit tests
        run: python3 run_tests.py
#       - name: Lint with flake8
#         run: |
#           pip3 install flake8
#           flake8 .
