on: push
name: test_on_push
jobs:
  gitHubActionForUnittest:
    name: GitHub Action for Python unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for Python unittest
      run: pip3 install setuptools && pip3 install -r requirements.txt && echo hello_world
